import { Suspense } from 'react';
import { Metadata } from 'next';
import { getServerSession } from 'next-auth';

import { Header, Login } from '@/components';
import { ReactQueryProvider, NextAuthProvider } from '@/providers';
import authOptions from '@/lib/auth';

import './globals.css';

export const metadata: Metadata = {
  title: 'Build-A-Body',
  description: 'Generated by create next app',
};

const RootLayout = async ({ children }: React.PropsWithChildren) => {
  const session = await getServerSession(authOptions);

  return (
    <html lang="en">
      <body className="flex h-screen w-screen bg-gray-900">
        <NextAuthProvider>
          <ReactQueryProvider>
            {session ? (
              <>
                <Header />
                <Suspense>{children}</Suspense>
              </>
            ) : (
              <Login />
            )}
          </ReactQueryProvider>
        </NextAuthProvider>
      </body>
    </html>
  );
};

export default RootLayout;
