import { Metadata } from 'next';

import { Header } from '@/components';
import { ReactQueryProvider, NextAuthProvider } from '@/providers';

import './globals.css';
import { Suspense } from 'react';

export const metadata: Metadata = {
  title: 'Build-A-Body',
  description: 'Generated by create next app',
};

const RootLayout = async ({ children }: React.PropsWithChildren) => {
  return (
    <html lang="en">
      <body className="flex h-screen w-screen bg-gray-900">
        <NextAuthProvider>
          <ReactQueryProvider>
            <Header />
            <Suspense>{children}</Suspense>
          </ReactQueryProvider>
        </NextAuthProvider>
      </body>
    </html>
  );
};

export default RootLayout;
