name: CI

on:
  pull_request:
    branches:
      - main
      - develop
  push:
    branches:
      - main
      - develop

jobs:
  build-and-start:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: '1.x'
          cache: bun
      - run: bun install
      - run: bun run build
      - run: bun run test
      - run: bun run playwright install --with-deps
      - run: bun run test:e2e
